# **Задание на повторение материала

In [1]:
import numpy as np

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [2]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [3]:
b1 = a.reshape(2, 6).copy()
b2 = a.reshape(3, 4).copy()
b3 = a.reshape(4, 3).copy()
b4 = a.reshape(6, 2).copy()
b5 = a.reshape(12, 1).copy()

In [4]:
b1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [5]:
b2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [6]:
b3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [7]:
b4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [8]:
b5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [9]:
c1 = a.reshape(2, -1).copy()
c2 = a.reshape(3, -1).copy()
c3 = a.reshape(4, -1).copy()
c4 = a.reshape(-1, 2).copy()
c5 = a.reshape(-1, 1).copy()

In [10]:
c1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [11]:
c2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
c3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [13]:
c4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [14]:
c5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [24]:
#Нет. Этим массивы нельзя назвать одномерными.
c5.ndim # выводим количество измерений

2

In [16]:
c5.shape #выводим размерность по каждому измерению

(12, 1)

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив

In [17]:
r = np.random.randn(3, 4)
print(f'{r.size=}')
r

12


array([[-1.35700557,  0.93865663,  0.71530077,  0.22847836],
       [-0.23196073, -0.09255509,  1.08036816, -1.06191147],
       [ 1.50410025, -1.19103103,  2.11398313, -0.47229187]])

In [40]:
rf = r.flatten()
print(f'{rf.size=}')
rf

rf.size=12


array([-1.35700557,  0.93865663,  0.71530077,  0.22847836, -0.23196073,
       -0.09255509,  1.08036816, -1.06191147,  1.50410025, -1.19103103,
        2.11398313, -0.47229187])

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [21]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [23]:
b = np.arange(20, 1, -2).reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [30]:
#массив a - одномерный
print(a.ndim)
#массив b - двумерный
print(b.ndim)

1
2


8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [38]:
a = np.zeros([2, 2])
b = np.ones([3, 2])
v = np.vstack([a, b])
print(f'{v.size=}')
v

v.size=10


array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?


In [48]:
a = np.arange(12)
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [49]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [50]:
B = A @ At
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [51]:
np.random.seed(42)

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [58]:
c = np.random.rand(16) * 16
c

array([12.93435757,  4.87382031,  1.56275382, 10.94772842,  7.0424399 ,
        1.95261176,  7.92283056,  0.55021634, 14.54912643,  4.14047971,
       10.60035655,  4.98737722,  8.32108834,  8.74736447,  2.95767129,
       15.51335404])

12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [59]:
C = c.reshape(4, 4)
C

array([[12.93435757,  4.87382031,  1.56275382, 10.94772842],
       [ 7.0424399 ,  1.95261176,  7.92283056,  0.55021634],
       [14.54912643,  4.14047971, 10.60035655,  4.98737722],
       [ 8.32108834,  8.74736447,  2.95767129, 15.51335404]])

In [61]:
D =  C * 10 + B
D

array([[134.3435757 ,  62.73820307,  38.62753824, 141.47728424],
       [ 84.424399  ,  69.52611758, 165.22830562, 127.50216338],
       [168.49126433, 127.40479706, 255.0035655 , 261.87377217],
       [115.21088339, 209.47364469, 241.57671288, 457.13354044]])

In [65]:
print(f'Определитель матрицы D = {np.linalg.det(D)}')

Определитель матрицы D = 34346399.02830989


In [66]:
print(f'Ранк матрицы D = {np.linalg.matrix_rank(D)}')

Ранк матрицы D = 4


In [67]:
print('Обратная матрица D')
D_inv = np.linalg.inv(D)
D_inv

Обратная матрица D


array([[ 0.00758422, -0.00031597,  0.0026154 , -0.00375736],
       [ 0.05231817,  0.20246522, -0.15367201,  0.01536987],
       [-0.00998823, -0.01257993,  0.01603565, -0.0025862 ],
       [-0.02060697, -0.08604861,  0.06128422, -0.00254177]])

In [68]:
# Проверка на обратную матрицу
D @ D_inv

array([[ 1.00000000e+00, -3.55271368e-15,  1.77635684e-15,
         0.00000000e+00],
       [ 4.44089210e-16,  1.00000000e+00, -8.88178420e-16,
        -2.22044605e-16],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00, -3.55271368e-15,
         1.00000000e+00]])

13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [73]:
D_inv[D_inv > 0] = 1
D_inv[D_inv < 0] = 0
D_inv

array([[1., 0., 1., 0.],
       [1., 1., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.]])

In [74]:
E = np.where(D_inv, B, C)
E

array([[  5.        ,   4.87382031,  23.        ,  10.94772842],
       [ 14.        ,  50.        ,   7.92283056, 122.        ],
       [ 14.54912643,   4.14047971, 149.        ,   4.98737722],
       [  8.32108834,   8.74736447, 212.        ,  15.51335404]])